
if [ -z $1 ]; then
    echo
    echo "usage: bash pick_best_model_for_full_training.sh <overall_results_folder_preffix>"
    echo "    "
    echo "    <overall_results_per_model_preffix>: summary folder preffix, generated by the plotting script (plot_evaluation_results_per_variant.R), more specifically: folder prefix where overall_results_per_model.tsv is"
    echo "    "
    echo "example: bash pick_best_model_for_full_training.sh plots_"
    echo
    exit
fi

train_script=$(cat BATCH_ID)

model_list=$(cat $train_script | sed -e 's/.*--model_id //g' | sed -e 's/ .*//g' | grep -v "_F")
pattern=$(echo $model_list | sed -e 's/ /\\\|/g')

for model in $model_list; do
    avg=$(cat ${1}[0-9]/overall_results_per_model.tsv | grep -w $model | cut -f 2 | awk '{ sum += $1 } END { if(NR==0) {print "NA"} else{print sum / NR} }')
    echo -e "$model\t$avg"
done > $train_script.model_r2pop.txt

best=$(cat $train_script.model_r2pop.txt | sort -k2,2g | tail -n 1 | cut -f 1)

cat $train_script | grep -w $best | sed -e 's/ --max_epochs 500 / --max_epochs 50000 /g' | sed -e "s/$best/${best}_F/g" > ${train_script}.best
file=$(basename ${train_script}.best)


echo
echo -e "Best model is $best, new full training model name: ${best}_F"
echo -e "Full training script created at ${train_script}.best"
echo -e "Mean r2 per feature across validation datasets listed at $train_script.model_r2pop.txt"
echo
echo -e "To run the training:"
echo -e "bash $file 1> $file.out 2> $file.log"
echo -e "bash $file 1> $file.out 2> $file.log" > train_best.sh
echo -e "Command stored at: $(readlink -e train_best.sh)"
